### ISSUE TITLE
QA failure at the end of 41_working_with_pipelines.adoc 

### ISSUE THREAD

**Issue by gutseb** [redhat-ai-services/ai-accelerator-bootcamp#2]
While testing the 41_pipelines process i ran into an issue. My accident model pipeline @failed. It looks like the logs saying that pip was not able to install some requirements.  @diego-torres or @strangiato perhaps we can take a look tomorrow if i have trouble figuring it out with a fresh brain. 

[accident-detection-mg228-2376030189-full.log](https://github.com/user-attachments/files/15751005/accident-detection-mg228-2376030189-full.log)
[accident-detection-mg228-2376030189-main-full.log](https://github.com/user-attachments/files/15751006/accident-detection-mg228-2376030189-main-full.log)

**Comment by diego-torres** [comment]
looks like it was unable to connect to this url to download the model:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: /rhods-public.s3.amazonaws.com/sample-data/accident-data/accident-sample.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f29eba5d910>: Failed to resolve 'https' ([Errno -2] Name or service not known)"))`

probably something to do with @gutseb connectivity?

@asheet , @thinko , can any of you guys have a chance to see if this is reproduced in your environments?

@gutseb , please try again.

**Comment by asheet** [comment]
got the same issue. I am able to reproduce.

**Comment by asheet** [comment]
It was the connection url that was making it fail. Fixed the url, now it's failing on the train model
